### ISSUE TITLE
How to read a capture file

### ISSUE THREAD

**Issue by DongDanBam** [bemasher/rtlcap#2]
When I look at my capture file in Windows Notepad, its all a bunch of garble.  What is the best text editor to view the capture data?  WIndows...  Windows...  Windows...

**Comment by bemasher** [comment]
Capture data consists of raw IQ (in-phase and quadrature) samples from the tuner, you won't be able to do anything meaningful with them in a text editor. Each sample is a pair of signed 8-bit integers. You'll want something like Audacity to view the amplitude and frequency content of the samples you captured.

![image](https://user-images.githubusercontent.com/79724/63643229-427fc600-c689-11e9-8b90-4784e2617660.png)

![image](https://user-images.githubusercontent.com/79724/63643241-76f38200-c689-11e9-925b-22664a070467.png)

![image](https://user-images.githubusercontent.com/79724/63643245-8c68ac00-c689-11e9-9674-a3a7f223ec4f.png)

![image](https://user-images.githubusercontent.com/79724/63643249-9c808b80-c689-11e9-9794-a01161da89bc.png)
Right click on the y-axis scale to zoom to fit.

![image](https://user-images.githubusercontent.com/79724/63643251-b1f5b580-c689-11e9-9077-384ca81904cb.png)

**Comment by DongDanBam** [comment]
Ahh.  Love Audicity.  Thanks.
